import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, expect, it, vi } from 'vitest'
import { ref } from 'vue'
import AnalystHomeView from '@/views/AnalystHomeView.vue'
import { productModeKey, type ProductMode } from '@/composables/productContext'
import router from '@/router'

const api = vi.hoisted(() => ({ listExperiments: vi.fn() }))
const navigate = vi.hoisted(() => vi.fn())
vi.mock('@/api/client', () => ({ workbenchApi: api }))
vi.mock('vue-router', async original => ({ ...await original<typeof import('vue-router')>(), useRouter: () => ({ push: navigate }) }))
function home(mode = ref<ProductMode>('workspace')) {
  return mount(AnalystHomeView, { global: { provide: { [productModeKey as symbol]: mode }, plugins: [router] } })
}
beforeEach(() => {
  vi.resetAllMocks()
  window.history.replaceState(null, '')
  api.listExperiments.mockResolvedValue({ items: [] })
})
it('starts only planning and passes the selected comparison without creating a record', async () => {
  const wrapper = home(); await flushPromises()
  expect(wrapper.get('h1').text()).toBe('规划一次评测')
  expect(wrapper.get('button[type="submit"]').text()).toContain('创建计划')
  expect(wrapper.find('.home-comparison-link').exists()).toBe(false)
  expect(wrapper.find('textarea').exists()).toBe(false)
  expect(wrapper.find('.recent-records').exists()).toBe(false)
  expect(wrapper.get('.home-example-link').attributes('href')).toBe('/examples')
  expect(navigate).not.toHaveBeenCalled()
  await wrapper.get('form').trigger('submit')
  expect(navigate).toHaveBeenLastCalledWith({ path: '/experiments/new', query: { comparison: 'MODEL_COMPARISON' } })
  await wrapper.get('input[value="HARNESS_UPLIFT"]').setValue()
  await wrapper.get('form').trigger('submit')
  expect(navigate).toHaveBeenLastCalledWith({ path: '/experiments/new', query: { comparison: 'HARNESS_UPLIFT' } })
  wrapper.unmount()
  const returned = home()
  expect((returned.get('input[value="HARNESS_UPLIFT"]').element as HTMLInputElement).checked).toBe(true)
  returned.unmount()
})
it('shows at most three server records with their actual identity and status', async () => {
  api.listExperiments.mockResolvedValue({ items: Array.from({ length: 4 }, (_, i) => ({ experiment_id: `saved-${i}`, name: `Saved ${i}`, status: 'completed', created_at: '2026-09-11T01:02:00Z' })) })
  const wrapper = home(); await flushPromises()
  expect(api.listExperiments).toHaveBeenCalledExactlyOnceWith({ limit: 3 })
  expect(wrapper.findAll('li')).toHaveLength(3)
  expect(wrapper.get('li a').attributes('href')).toBe('/experiments/saved-0')
  expect(wrapper.get('time').attributes('datetime')).toBe('2026-09-11T01:02:00Z')
  expect(wrapper.get('[data-status]').attributes('data-status')).toBe('completed')
  wrapper.unmount()
})
it('distinguishes failed reads from empty records and retries explicitly', async () => {
  api.listExperiments.mockRejectedValueOnce(new Error('unavailable'))
  const wrapper = home(); await flushPromises()
  expect(wrapper.get('[role="alert"]').text()).toContain('最近记录加载失败')
  expect(wrapper.find('.recent-records').exists()).toBe(false)
  await wrapper.get('[role="alert"] button').trigger('click'); await flushPromises()
  expect(wrapper.find('[role="alert"]').exists()).toBe(false)
  expect(wrapper.find('.recent-records').exists()).toBe(false)
  expect(api.listExperiments).toHaveBeenCalledTimes(2)
  wrapper.unmount()
})
it('does not fetch workspace records in demo or unknown mode and discards stale responses', async () => {
  const mode = ref<ProductMode>('unknown')
  const wrapper = home(mode); await flushPromises()
  expect(wrapper.get('h1').text()).toBe('首页')
  expect(wrapper.find('.home-comparison-link').exists()).toBe(false)
  mode.value = 'demo'; await flushPromises()
  expect(wrapper.get('h1').text()).toBe('查看评测案例')
  expect(wrapper.get('.home-comparison-link').attributes('href')).toBe('/examples?example=comparison')
  expect(wrapper.get('.home-example-link').text()).toContain('其他示例')
  expect(api.listExperiments).not.toHaveBeenCalled()
  expect(wrapper.find('form').exists()).toBe(false)
  let resolve!: (value: unknown) => void
  api.listExperiments.mockImplementationOnce(() => new Promise(done => { resolve = done }))
  mode.value = 'workspace'; await flushPromises()
  expect(wrapper.find('form').exists()).toBe(true)
  mode.value = 'demo'; await flushPromises()
  resolve({ items: [{ experiment_id: 'stale', name: 'Stale record' }] }); await flushPromises()
  expect(wrapper.text()).not.toContain('Stale record')
  expect(wrapper.find('form').exists()).toBe(false)
  wrapper.unmount()
})
it('keeps legacy example URLs compatible', async () => {
  await router.push('/analyst?example=historical')
  expect(router.currentRoute.value.fullPath).toBe('/examples?example=historical')
  await router.push('/analyst?example=offline')
  expect(router.currentRoute.value.fullPath).toBe('/examples?example=offline')
  expect(router.getRoutes().find(route => route.path === '/')?.redirect).toBe('/analyst')
})
