import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { localExecutionApi } from '@/api/localExecution'
import LocalExecutionPanel from '@/components/LocalExecutionPanel.vue'
import type { SavedPlan } from '@/api/localPlans'
import type { ExecutionState } from '@/api/localExecution'
import { preferences } from '@/composables/preferences'
vi.mock('@/api/localExecution', () => ({ localExecutionApi: { status: vi.fn(), state: vi.fn(), authorize: vi.fn(), cancel: vi.fn() } }))
const plan = { plan_id: 'plan-1', plan_digest: 'sha256:test', preflight: { material: { request: { budget: { wall_time_seconds: 20 } } } } } as SavedPlan
const initial: ExecutionState = { status: 'NOT_AUTHORIZED', mode: 'FAKE_CODEX', real_execution_enabled: false, attempt: null, result: null }
const queued: ExecutionState = { ...initial, status: 'QUEUED', attempt: { run_id: 'local-run-1', attempt_number: 0, cancellation_requested: false, authorization: { expires_at: '2026-10-09T22:00:00Z', digest: 'sha256:auth' } } }
beforeEach(() => { vi.resetAllMocks(); preferences.language = 'zh-CN'; vi.mocked(localExecutionApi.status).mockResolvedValue({ enabled: true, mode: 'FAKE_CODEX', real_execution_enabled: false, model_calls_allowed: 0, reason_codes: [] }); vi.mocked(localExecutionApi.state).mockResolvedValue(initial); vi.mocked(localExecutionApi.authorize).mockResolvedValue(queued); vi.mocked(localExecutionApi.cancel).mockResolvedValue({ ...queued, status: 'CANCELLED' }) })
async function panel(stale = false) { const wrapper = mount(LocalExecutionPanel, { props: { plan, token: 'page-only-token', stale } }); await flushPromises(); return wrapper }
describe('separate execution authorization', () => {
  it('never authorizes from loading or plan confirmation', async () => { const w = await panel(); expect(localExecutionApi.authorize).not.toHaveBeenCalled(); expect(w.get('[data-test="authorize"]').attributes('disabled')).toBeDefined(); expect(w.text()).toContain('计划确认不等于执行授权'); expect(w.text()).toContain('真实 Codex 默认关闭') })
  it('requires separate confirmation and shows the persisted queue', async () => { const w = await panel(); await w.get('[data-test="execute-confirmation"]').setValue(true); await w.get('[data-test="authorize"]').trigger('click'); await flushPromises(); expect(localExecutionApi.authorize).toHaveBeenCalledWith(plan, expect.any(String), 'page-only-token'); expect(w.text()).toContain('等待独立 Worker'); expect(w.find('[data-test="authorize"]').exists()).toBe(false) })
  it('does not permit a stale plan', async () => { const w = await panel(true); expect(w.get('[data-test="execute-confirmation"]').attributes('disabled')).toBeDefined(); expect(w.text()).toContain('旧计划不能执行'); expect(localExecutionApi.authorize).not.toHaveBeenCalled() })
  it('retries a lost response with the same request key and a fresh confirmation', async () => { vi.mocked(localExecutionApi.authorize).mockRejectedValueOnce(new Error('lost')); const w = await panel(); for (let i = 0; i < 2; i++) { await w.get('[data-test="execute-confirmation"]').setValue(true); await w.get('[data-test="authorize"]').trigger('click'); await flushPromises() }; const calls = vi.mocked(localExecutionApi.authorize).mock.calls; expect(calls).toHaveLength(2); expect(calls[0]?.[1]).toBe(calls[1]?.[1]) })
  it('reads an existing attempt after refresh and requests cancellation', async () => { vi.mocked(localExecutionApi.state).mockResolvedValue(queued); const w = await panel(); expect(w.find('[data-test="authorize"]').exists()).toBe(false); await w.get('[data-test="cancel-execution"]').trigger('click'); await flushPromises(); expect(localExecutionApi.cancel).toHaveBeenCalledWith('plan-1', 'page-only-token'); expect(w.text()).toContain('已取消') })
  it('fails closed on evidence tampering without a replacement result', async () => { vi.mocked(localExecutionApi.state).mockRejectedValue({ response: { data: { error: { code: 'EXECUTION_EVIDENCE_INTEGRITY_ERROR' } } } }); const w = await panel(); expect(w.text()).toContain('EXECUTION_EVIDENCE_INTEGRITY_ERROR'); expect(w.find('[data-test="execution-result"]').exists()).toBe(false); expect(w.find('[data-test="authorize"]').exists()).toBe(false) })
  it('shows independent checks and synthetic scope instead of model claims', async () => { vi.mocked(localExecutionApi.state).mockResolvedValue({ ...queued, status: 'VERIFIED_FAIL', result: { status: 'VERIFIED_FAIL', reason_code: 'verified_fail', acceptance: 'RECORDED_FAIL', run_id: 'local-run-1', digest: 'sha256:result', episode_id: 'sha256:episode', model_calls: 0, model_cost_usd: 0, episode: { event_count: 4, changed_file_count: 0, verifier_check_count: 3, trace_digest: 'sha256:trace', workspace_output_digest: 'sha256:workspace', acceptance: 'RECORDED_FAIL' } } }); const w = await panel(); expect(w.text()).toContain('独立验收失败 · Fake'); expect(w.text()).toContain('独立检查: 3'); expect(w.text()).toContain('不能证明真实模型能力') })
  it('clears old authorization controls on token and plan changes', async () => { const w = await panel(); await w.get('[data-test="execute-confirmation"]').setValue(true); await w.setProps({ token: 'changed-token' }); await flushPromises(); expect((w.get('[data-test="execute-confirmation"]').element as HTMLInputElement).checked).toBe(false) })
})
